Add missing Browser#getBrowserType method
Bug 561299: java.lang.NoSuchMethodError:
org.eclipse.swt.browser.Browser.getBrowserType()
https://bugs.eclipse.org/bugs/show_bug.cgi?id=561299

Change-Id: I161b6310b0db91a9f557ab135c24b6dff3776fc4