Workaround: add package imports for objenesis
The JUnit integration in Eclipse does not include transitive
dependencies for PDE projects, resulting in NoClassDefFoundErrors
for objenesis when executing mockito code.

To work around this problem, explicitly import the obenesis package
in the test bundle's manifests.

Change-Id: I4fdacf3524fd80db635d635b82420b0755ea5330
Signed-off-by: Ralf Sternberg <rsternberg@eclipsesource.com>