Import JUnit using require-bundle
When importing JUnit using import-package, the JUnit launcher in Eclipse
fails occasionally with NoClassDefFoundErrors for hamcrest classes.
Importing JUnit using require-bundle is the only workaround I can
currently find.